//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("NorthwindModel", "Orders_FK00", "Customers", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SdtBusinessApplication.Web.Customer), "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SdtBusinessApplication.Web.Orders), true)]
[assembly: EdmRelationshipAttribute("NorthwindModel", "Orders_FK02", "Employees", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SdtBusinessApplication.Web.Employee), "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SdtBusinessApplication.Web.Orders), true)]

#endregion

namespace SdtBusinessApplication.Web
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class NorthwindEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new NorthwindEntities object using the connection string found in the 'NorthwindEntities' section of the application configuration file.
        /// </summary>
        public NorthwindEntities() : base("name=NorthwindEntities", "NorthwindEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NorthwindEntities object.
        /// </summary>
        public NorthwindEntities(string connectionString) : base(connectionString, "NorthwindEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NorthwindEntities object.
        /// </summary>
        public NorthwindEntities(EntityConnection connection) : base(connection, "NorthwindEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Customer> Customers
        {
            get
            {
                if ((_Customers == null))
                {
                    _Customers = base.CreateObjectSet<Customer>("Customers");
                }
                return _Customers;
            }
        }
        private ObjectSet<Customer> _Customers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Employee> Employees
        {
            get
            {
                if ((_Employees == null))
                {
                    _Employees = base.CreateObjectSet<Employee>("Employees");
                }
                return _Employees;
            }
        }
        private ObjectSet<Employee> _Employees;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Orders> Orders
        {
            get
            {
                if ((_Orders == null))
                {
                    _Orders = base.CreateObjectSet<Orders>("Orders");
                }
                return _Orders;
            }
        }
        private ObjectSet<Orders> _Orders;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Customers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomers(Customer customer)
        {
            base.AddObject("Customers", customer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Employees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmployees(Employee employee)
        {
            base.AddObject("Employees", employee);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Orders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrders(Orders orders)
        {
            base.AddObject("Orders", orders);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NorthwindModel", Name="Customer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Customer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="customer_ID">Initial value of the Customer_ID property.</param>
        /// <param name="company_Name">Initial value of the Company_Name property.</param>
        public static Customer CreateCustomer(global::System.String customer_ID, global::System.String company_Name)
        {
            Customer customer = new Customer();
            customer.Customer_ID = customer_ID;
            customer.Company_Name = company_Name;
            return customer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Customer_ID
        {
            get
            {
                return _Customer_ID;
            }
            set
            {
                if (_Customer_ID != value)
                {
                    OnCustomer_IDChanging(value);
                    ReportPropertyChanging("Customer_ID");
                    _Customer_ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Customer_ID");
                    OnCustomer_IDChanged();
                }
            }
        }
        private global::System.String _Customer_ID;
        partial void OnCustomer_IDChanging(global::System.String value);
        partial void OnCustomer_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Company_Name
        {
            get
            {
                return _Company_Name;
            }
            set
            {
                OnCompany_NameChanging(value);
                ReportPropertyChanging("Company_Name");
                _Company_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Company_Name");
                OnCompany_NameChanged();
            }
        }
        private global::System.String _Company_Name;
        partial void OnCompany_NameChanging(global::System.String value);
        partial void OnCompany_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Contact_Name
        {
            get
            {
                return _Contact_Name;
            }
            set
            {
                OnContact_NameChanging(value);
                ReportPropertyChanging("Contact_Name");
                _Contact_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Contact_Name");
                OnContact_NameChanged();
            }
        }
        private global::System.String _Contact_Name;
        partial void OnContact_NameChanging(global::System.String value);
        partial void OnContact_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Contact_Title
        {
            get
            {
                return _Contact_Title;
            }
            set
            {
                OnContact_TitleChanging(value);
                ReportPropertyChanging("Contact_Title");
                _Contact_Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Contact_Title");
                OnContact_TitleChanged();
            }
        }
        private global::System.String _Contact_Title;
        partial void OnContact_TitleChanging(global::System.String value);
        partial void OnContact_TitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Postal_Code
        {
            get
            {
                return _Postal_Code;
            }
            set
            {
                OnPostal_CodeChanging(value);
                ReportPropertyChanging("Postal_Code");
                _Postal_Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Postal_Code");
                OnPostal_CodeChanged();
            }
        }
        private global::System.String _Postal_Code;
        partial void OnPostal_CodeChanging(global::System.String value);
        partial void OnPostal_CodeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "Orders_FK00", "Orders")]
        public EntityCollection<Orders> Orders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Orders>("NorthwindModel.Orders_FK00", "Orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Orders>("NorthwindModel.Orders_FK00", "Orders", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NorthwindModel", Name="Employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Employee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="employee_ID">Initial value of the Employee_ID property.</param>
        /// <param name="last_Name">Initial value of the Last_Name property.</param>
        /// <param name="first_Name">Initial value of the First_Name property.</param>
        public static Employee CreateEmployee(global::System.Int32 employee_ID, global::System.String last_Name, global::System.String first_Name)
        {
            Employee employee = new Employee();
            employee.Employee_ID = employee_ID;
            employee.Last_Name = last_Name;
            employee.First_Name = first_Name;
            return employee;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Employee_ID
        {
            get
            {
                return _Employee_ID;
            }
            set
            {
                if (_Employee_ID != value)
                {
                    OnEmployee_IDChanging(value);
                    ReportPropertyChanging("Employee_ID");
                    _Employee_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Employee_ID");
                    OnEmployee_IDChanged();
                }
            }
        }
        private global::System.Int32 _Employee_ID;
        partial void OnEmployee_IDChanging(global::System.Int32 value);
        partial void OnEmployee_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Last_Name
        {
            get
            {
                return _Last_Name;
            }
            set
            {
                OnLast_NameChanging(value);
                ReportPropertyChanging("Last_Name");
                _Last_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Last_Name");
                OnLast_NameChanged();
            }
        }
        private global::System.String _Last_Name;
        partial void OnLast_NameChanging(global::System.String value);
        partial void OnLast_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String First_Name
        {
            get
            {
                return _First_Name;
            }
            set
            {
                OnFirst_NameChanging(value);
                ReportPropertyChanging("First_Name");
                _First_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("First_Name");
                OnFirst_NameChanged();
            }
        }
        private global::System.String _First_Name;
        partial void OnFirst_NameChanging(global::System.String value);
        partial void OnFirst_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Photo
        {
            get
            {
                return StructuralObject.GetValidValue(_Photo);
            }
            set
            {
                OnPhotoChanging(value);
                ReportPropertyChanging("Photo");
                _Photo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Photo");
                OnPhotoChanged();
            }
        }
        private global::System.Byte[] _Photo;
        partial void OnPhotoChanging(global::System.Byte[] value);
        partial void OnPhotoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "Orders_FK02", "Orders")]
        public EntityCollection<Orders> Orders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Orders>("NorthwindModel.Orders_FK02", "Orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Orders>("NorthwindModel.Orders_FK02", "Orders", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NorthwindModel", Name="Orders")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Orders : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Orders object.
        /// </summary>
        /// <param name="order_ID">Initial value of the Order_ID property.</param>
        /// <param name="customer_ID">Initial value of the Customer_ID property.</param>
        public static Orders CreateOrders(global::System.Int32 order_ID, global::System.String customer_ID)
        {
            Orders orders = new Orders();
            orders.Order_ID = order_ID;
            orders.Customer_ID = customer_ID;
            return orders;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Order_ID
        {
            get
            {
                return _Order_ID;
            }
            set
            {
                if (_Order_ID != value)
                {
                    OnOrder_IDChanging(value);
                    ReportPropertyChanging("Order_ID");
                    _Order_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Order_ID");
                    OnOrder_IDChanged();
                }
            }
        }
        private global::System.Int32 _Order_ID;
        partial void OnOrder_IDChanging(global::System.Int32 value);
        partial void OnOrder_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Customer_ID
        {
            get
            {
                return _Customer_ID;
            }
            set
            {
                OnCustomer_IDChanging(value);
                ReportPropertyChanging("Customer_ID");
                _Customer_ID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Customer_ID");
                OnCustomer_IDChanged();
            }
        }
        private global::System.String _Customer_ID;
        partial void OnCustomer_IDChanging(global::System.String value);
        partial void OnCustomer_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Employee_ID
        {
            get
            {
                return _Employee_ID;
            }
            set
            {
                OnEmployee_IDChanging(value);
                ReportPropertyChanging("Employee_ID");
                _Employee_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Employee_ID");
                OnEmployee_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _Employee_ID;
        partial void OnEmployee_IDChanging(Nullable<global::System.Int32> value);
        partial void OnEmployee_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ship_Name
        {
            get
            {
                return _Ship_Name;
            }
            set
            {
                OnShip_NameChanging(value);
                ReportPropertyChanging("Ship_Name");
                _Ship_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ship_Name");
                OnShip_NameChanged();
            }
        }
        private global::System.String _Ship_Name;
        partial void OnShip_NameChanging(global::System.String value);
        partial void OnShip_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ship_Address
        {
            get
            {
                return _Ship_Address;
            }
            set
            {
                OnShip_AddressChanging(value);
                ReportPropertyChanging("Ship_Address");
                _Ship_Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ship_Address");
                OnShip_AddressChanged();
            }
        }
        private global::System.String _Ship_Address;
        partial void OnShip_AddressChanging(global::System.String value);
        partial void OnShip_AddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ship_City
        {
            get
            {
                return _Ship_City;
            }
            set
            {
                OnShip_CityChanging(value);
                ReportPropertyChanging("Ship_City");
                _Ship_City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ship_City");
                OnShip_CityChanged();
            }
        }
        private global::System.String _Ship_City;
        partial void OnShip_CityChanging(global::System.String value);
        partial void OnShip_CityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ship_Region
        {
            get
            {
                return _Ship_Region;
            }
            set
            {
                OnShip_RegionChanging(value);
                ReportPropertyChanging("Ship_Region");
                _Ship_Region = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ship_Region");
                OnShip_RegionChanged();
            }
        }
        private global::System.String _Ship_Region;
        partial void OnShip_RegionChanging(global::System.String value);
        partial void OnShip_RegionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ship_Postal_Code
        {
            get
            {
                return _Ship_Postal_Code;
            }
            set
            {
                OnShip_Postal_CodeChanging(value);
                ReportPropertyChanging("Ship_Postal_Code");
                _Ship_Postal_Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ship_Postal_Code");
                OnShip_Postal_CodeChanged();
            }
        }
        private global::System.String _Ship_Postal_Code;
        partial void OnShip_Postal_CodeChanging(global::System.String value);
        partial void OnShip_Postal_CodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ship_Country
        {
            get
            {
                return _Ship_Country;
            }
            set
            {
                OnShip_CountryChanging(value);
                ReportPropertyChanging("Ship_Country");
                _Ship_Country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ship_Country");
                OnShip_CountryChanged();
            }
        }
        private global::System.String _Ship_Country;
        partial void OnShip_CountryChanging(global::System.String value);
        partial void OnShip_CountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Ship_Via
        {
            get
            {
                return _Ship_Via;
            }
            set
            {
                OnShip_ViaChanging(value);
                ReportPropertyChanging("Ship_Via");
                _Ship_Via = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ship_Via");
                OnShip_ViaChanged();
            }
        }
        private Nullable<global::System.Int32> _Ship_Via;
        partial void OnShip_ViaChanging(Nullable<global::System.Int32> value);
        partial void OnShip_ViaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Order_Date
        {
            get
            {
                return _Order_Date;
            }
            set
            {
                OnOrder_DateChanging(value);
                ReportPropertyChanging("Order_Date");
                _Order_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Order_Date");
                OnOrder_DateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Order_Date;
        partial void OnOrder_DateChanging(Nullable<global::System.DateTime> value);
        partial void OnOrder_DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Required_Date
        {
            get
            {
                return _Required_Date;
            }
            set
            {
                OnRequired_DateChanging(value);
                ReportPropertyChanging("Required_Date");
                _Required_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Required_Date");
                OnRequired_DateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Required_Date;
        partial void OnRequired_DateChanging(Nullable<global::System.DateTime> value);
        partial void OnRequired_DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Shipped_Date
        {
            get
            {
                return _Shipped_Date;
            }
            set
            {
                OnShipped_DateChanging(value);
                ReportPropertyChanging("Shipped_Date");
                _Shipped_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Shipped_Date");
                OnShipped_DateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Shipped_Date;
        partial void OnShipped_DateChanging(Nullable<global::System.DateTime> value);
        partial void OnShipped_DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Freight
        {
            get
            {
                return _Freight;
            }
            set
            {
                OnFreightChanging(value);
                ReportPropertyChanging("Freight");
                _Freight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Freight");
                OnFreightChanged();
            }
        }
        private Nullable<global::System.Decimal> _Freight;
        partial void OnFreightChanging(Nullable<global::System.Decimal> value);
        partial void OnFreightChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "Orders_FK00", "Customers")]
        public Customer Customers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("NorthwindModel.Orders_FK00", "Customers").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("NorthwindModel.Orders_FK00", "Customers").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Customer> CustomersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("NorthwindModel.Orders_FK00", "Customers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Customer>("NorthwindModel.Orders_FK00", "Customers", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "Orders_FK02", "Employees")]
        public Employee Employees
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("NorthwindModel.Orders_FK02", "Employees").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("NorthwindModel.Orders_FK02", "Employees").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> EmployeesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("NorthwindModel.Orders_FK02", "Employees");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("NorthwindModel.Orders_FK02", "Employees", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
